export enum GIZMO_TYPE {
  TABLE = 'GizmoTable',
  ROW = 'GizmoRow',
  SHORT_TEXT_INPUT = 'GizmoShortTextInput',
  LONG_TEXT_INPUT = 'GizmoLongTextInput',
  COLOR_STATUS = 'GizmoGreenYellowRedStatusInput',
  PAGE = 'GizmoPage',
  TEXT = 'GizmoTextContent',
  DROPDOWN_OPTION = 'GizmoDropdownOption',
  DROPDOWN = 'GizmoDropdownInput',
  DATE_INPUT = 'GizmoDateInput',
  NUMBER_INPUT = 'GizmoNumberInput',
  YES_NO_INPUT = 'GizmoYesNoInput',
  CHECKBOX_INPUT = 'GizmoCheckboxInput',
  DOWNLOAD = 'GizmoAttachment',
  ATTACHMENT_IMAGE = 'GizmoAttachmentImage',
  VIDEO = 'GizmoVideo',
  URL = 'GizmoUrl',
  UPLOAD_INPUT = 'GizmoAttachmentInput',
  SNAPSHOT_INPUT = 'GizmoAttachmentSnapPictureInput',
  IMAGE_INPUT = 'GizmoAttachmentImageInput',
  TASK_LIST = 'GizmoTaskList',
  PERSON = 'GizmoPersonInput',
  ASSIGNEE = 'GizmoAssignmentInput'
}
